name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    # Run all shell steps from the folder that contains pom.xml
    defaults:
      run:
        working-directory: employee-pension-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build & test
        run: mvn -B clean verify

      - name: Upload JAR artifact (optional)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: employee-pension-app-jar
          path: target/*.jar
